### PR TITLE
Fix compilation on Ubuntu 20.04

### PR DESCRIPTION
**Pull request by ankane**
Compilation currently fails with GCC 9.

```text
/home/runner/work/torch.rb/torch.rb/vendor/bundle/ruby/3.1.0/gems/rice-4.3.2/include/rice/rice.hpp:1141:109:   required from here
/usr/include/c++/9/type_traits:131:12: error: incomplete type ‘std::is_copy_constructible<std::_Tuple_impl<2, std::any> >’ used in nested name specifier
```

Ref: https://stackoverflow.com/questions/65163455/stdany-containing-stdtuplestdany-fails-to-compile

### CODE REVIEW

**Comment by ankane** [comment]
Thanks

**Comment by cfis** [comment]
That looks like a nice improvement - thanks!

**Comment by jasonroelofs** [comment]
Version 4.3.3 is pushed with this fix.

**Comment by ankane** [comment]
Great, thanks.

**Pull request merged**
